# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='curr_available_amount_if_credit_row',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='expiry_time_of_credited_amount',
            field=models.DateTimeField(verbose_name=datetime.datetime(2030, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 8, 37, 39, 615543)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet2user_details',
            field=models.BigIntegerField(),
        ),
    ]
