# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20160123_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='curr_available_amount_if_credit_row',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 9, 12, 19, 311955)),
        ),
    ]
